#![doc = "Dynamic style and layout invalidation helpers for Sylphos."]

use crate::{CssomInvalidation, CssomMutation, DirtyFlags, InvalidationSet};

/// Runtime style/layout generation counters used by the app render bridge.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct DynamicLayoutState {
    /// CSSOM revision observed by layout.
    pub style_revision: u64,

    /// Layout revision observed by paint.
    pub layout_revision: u64,

    /// Paint revision observed by renderer.
    pub paint_revision: u64,
}

impl DynamicLayoutState {
    /// Records a CSSOM invalidation and advances affected generations.
    pub fn apply_cssom_invalidation(&mut self, invalidation: CssomInvalidation) {
        if invalidation.style {
            self.style_revision = self.style_revision.wrapping_add(1);
        }
        if invalidation.layout {
            self.layout_revision = self.layout_revision.wrapping_add(1);
        }
        if invalidation.paint {
            self.paint_revision = self.paint_revision.wrapping_add(1);
        }
    }

    /// Records a forced full reflow.
    pub fn force_full_reflow(&mut self) {
        self.style_revision = self.style_revision.wrapping_add(1);
        self.layout_revision = self.layout_revision.wrapping_add(1);
        self.paint_revision = self.paint_revision.wrapping_add(1);
    }
}

/// Dynamic style update generated by JS, CSSOM APIs, or host actions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DynamicStyleUpdate {
    /// Original mutation.
    pub mutation: CssomMutation,

    /// Diagnostic origin, for example `script`, `devtools`, or `host`.
    pub origin: String,
}

impl DynamicStyleUpdate {
    /// Creates a script-origin update.
    #[must_use]
    pub fn from_script(mutation: CssomMutation) -> Self {
        Self {
            mutation,
            origin: "script".to_owned(),
        }
    }
}

/// Converts a CSSOM invalidation into the existing dirty flag system.
#[must_use]
pub const fn cssom_invalidation_to_dirty_flags(invalidation: CssomInvalidation) -> DirtyFlags {
    let mut flags = DirtyFlags::none();

    if invalidation.style {
        flags.style = true;
    }
    if invalidation.layout {
        flags.layout = true;
        flags.hit_test = true;
    }
    if invalidation.paint {
        flags.paint = true;
    }

    flags
}

/// Converts a viewport-sized CSSOM invalidation into an invalidation set.
#[must_use]
pub fn cssom_invalidation_to_set(
    invalidation: CssomInvalidation,
    width: f32,
    height: f32,
) -> InvalidationSet {
    let flags = cssom_invalidation_to_dirty_flags(invalidation);
    let _ = (width, height);
    InvalidationSet::new(flags)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dynamic_state_advances_revisions() {
        let mut state = DynamicLayoutState::default();
        state.apply_cssom_invalidation(CssomInvalidation::full());
        assert_eq!(state.style_revision, 1);
        assert_eq!(state.layout_revision, 1);
        assert_eq!(state.paint_revision, 1);
    }
}
