#![doc = "Mutable DOM model, mutation APIs, and render-document synchronization."]
#![allow(clippy::too_many_lines, clippy::missing_const_for_fn)]

use std::collections::BTreeMap;

use crate::events::{EventDispatchResult, ScriptHook, ScriptHookQueue};
use crate::{
    DefaultAction, DirtyFlags, DomEvent, DomEventKind, DomEventPayload, FormBlock, FormControlKind,
    FormMethod, InvalidationSet, RenderBlock, RenderDocument,
};

/// Stable node id inside a [`DomRuntime`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct DomNodeId(u64);

impl DomNodeId {
    /// Raw numeric value.
    #[must_use]
    pub const fn value(self) -> u64 {
        self.0
    }

    /// Creates a node id for deterministic tests and engine diagnostics.
    #[must_use]
    pub const fn from_raw_for_tests(value: u64) -> Self {
        Self(value)
    }
}

/// Mutable DOM node kind used by the runtime model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DomNodeKind {
    /// Synthetic root node.
    Root,

    /// Block-level node aligned to a `RenderBlock` index.
    Block,

    /// Text node.
    Text,

    /// Link node.
    Link,

    /// Image node.
    Image,

    /// Form node.
    Form,

    /// Form control node.
    FormControl,

    /// Future script placeholder.
    ScriptPlaceholder,

    /// Unknown or generic node.
    Unknown,
}

/// Mutable DOM node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DomNode {
    /// Node id.
    pub id: DomNodeId,

    /// Optional parent node.
    pub parent: Option<DomNodeId>,

    /// Child nodes in source/render order.
    pub children: Vec<DomNodeId>,

    /// Node kind.
    pub kind: DomNodeKind,

    /// Source-ish tag name, when available.
    pub tag: String,

    /// Attribute map.
    pub attributes: BTreeMap<String, String>,

    /// Text/value payload.
    pub text: String,

    /// Render block index when this node maps to one block.
    pub block_index: Option<usize>,

    /// Form id when this node maps to a form.
    pub form_id: Option<u64>,

    /// Control id when this node maps to a form control.
    pub control_id: Option<u64>,
}

impl DomNode {
    fn new(id: DomNodeId, kind: DomNodeKind, tag: impl Into<String>) -> Self {
        Self {
            id,
            parent: None,
            children: Vec::new(),
            kind,
            tag: tag.into(),
            attributes: BTreeMap::new(),
            text: String::new(),
            block_index: None,
            form_id: None,
            control_id: None,
        }
    }
}

/// Mutation kind recorded by the runtime.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DomMutationKind {
    /// Node was inserted.
    InsertNode {
        /// Parent receiving the inserted node.
        parent: DomNodeId,

        /// Inserted node id.
        node: DomNodeId,
    },

    /// Node was removed.
    RemoveNode {
        /// Removed node id.
        node: DomNodeId,
    },

    /// Attribute was set.
    SetAttribute {
        /// Attribute name.
        name: String,

        /// Attribute value.
        value: String,
    },

    /// Attribute was removed.
    RemoveAttribute {
        /// Attribute name.
        name: String,
    },

    /// Text content changed.
    SetText {
        /// New text content.
        value: String,
    },

    /// Form-control value changed.
    SetFormValue {
        /// Updated control id.
        control_id: u64,

        /// New control value.
        value: String,
    },

    /// Form-control focus changed.
    SetFocus {
        /// Focused control id, or `None` when focus was cleared.
        control_id: Option<u64>,
    },

    /// Event was dispatched.
    DispatchEvent {
        /// Dispatched event kind.
        event: DomEventKind,
    },
}

/// Mutation record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DomMutation {
    /// Monotonic sequence.
    pub sequence: u64,

    /// Target node.
    pub target: DomNodeId,

    /// Mutation kind.
    pub kind: DomMutationKind,

    /// Dirty flags generated by this mutation.
    pub dirty: DirtyFlags,
}

/// Mutable DOM runtime for one page snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DomRuntime {
    root: DomNodeId,
    nodes: BTreeMap<DomNodeId, DomNode>,
    next_node_id: u64,
    next_event_id: u64,
    sequence: u64,
    focused_control_id: Option<u64>,
    invalidation: InvalidationSet,
    mutations: Vec<DomMutation>,
    script_hooks: ScriptHookQueue,
}

impl Default for DomRuntime {
    fn default() -> Self {
        Self::empty()
    }
}

impl DomRuntime {
    /// Creates an empty runtime with only a synthetic root node.
    #[must_use]
    pub fn empty() -> Self {
        let root = DomNodeId(1);
        let mut nodes = BTreeMap::new();
        nodes.insert(root, DomNode::new(root, DomNodeKind::Root, "#root"));

        Self {
            root,
            nodes,
            next_node_id: 2,
            next_event_id: 1,
            sequence: 1,
            focused_control_id: None,
            invalidation: InvalidationSet::default(),
            mutations: Vec::new(),
            script_hooks: ScriptHookQueue::default(),
        }
    }

    /// Builds a mutable DOM runtime from the current render document.
    #[must_use]
    pub fn from_render_document(document: &RenderDocument) -> Self {
        let mut runtime = Self::empty();
        runtime.rebuild_from_render_document(document);
        runtime
    }

    /// Rebuilds runtime nodes from a render document while preserving runtime counters.
    pub fn rebuild_from_render_document(&mut self, document: &RenderDocument) {
        let root = self.root;
        self.nodes.clear();
        self.nodes
            .insert(root, DomNode::new(root, DomNodeKind::Root, "#root"));
        self.next_node_id = root.0.saturating_add(1);
        self.focused_control_id = None;

        for (index, block) in document.blocks.iter().enumerate() {
            self.add_block_node(root, index, block);
        }

        self.mark(
            root,
            DirtyFlags::structure(),
            DomMutationKind::SetText {
                value: "runtime rebuilt".to_owned(),
            },
        );
    }

    /// Returns root id.
    #[must_use]
    pub const fn root_id(&self) -> DomNodeId {
        self.root
    }

    /// Returns a node by id.
    #[must_use]
    pub fn node(&self, id: DomNodeId) -> Option<&DomNode> {
        self.nodes.get(&id)
    }

    /// Returns all nodes in deterministic id order.
    pub fn nodes(&self) -> impl Iterator<Item = &DomNode> {
        self.nodes.values()
    }

    /// Returns current focused control id.
    #[must_use]
    pub const fn focused_control_id(&self) -> Option<u64> {
        self.focused_control_id
    }

    /// Returns current invalidation set.
    #[must_use]
    pub const fn invalidation(&self) -> &InvalidationSet {
        &self.invalidation
    }

    /// Clears and returns invalidation state.
    #[must_use]
    pub fn take_invalidation(&mut self) -> InvalidationSet {
        self.invalidation.take()
    }

    /// Returns mutation records.
    #[must_use]
    pub fn mutations(&self) -> &[DomMutation] {
        &self.mutations
    }

    /// Drains mutation records.
    #[must_use]
    pub fn drain_mutations(&mut self) -> Vec<DomMutation> {
        std::mem::take(&mut self.mutations)
    }

    /// Returns queued script hooks.
    #[must_use]
    pub fn script_hooks(&self) -> &ScriptHookQueue {
        &self.script_hooks
    }

    /// Drains queued script hooks.
    #[must_use]
    pub fn drain_script_hooks(&mut self) -> Vec<ScriptHook> {
        self.script_hooks.drain()
    }

    /// Sets an attribute on a node.
    #[must_use]
    pub fn set_attribute(
        &mut self,
        node_id: DomNodeId,
        name: impl Into<String>,
        value: impl Into<String>,
    ) -> bool {
        let name = name.into().to_ascii_lowercase();
        let value = value.into();
        let Some(node) = self.nodes.get_mut(&node_id) else {
            return false;
        };
        node.attributes.insert(name.clone(), value.clone());
        self.mark(
            node_id,
            DirtyFlags::attributes(),
            DomMutationKind::SetAttribute { name, value },
        );
        true
    }

    /// Removes an attribute from a node.
    #[must_use]
    pub fn remove_attribute(&mut self, node_id: DomNodeId, name: &str) -> bool {
        let Some(node) = self.nodes.get_mut(&node_id) else {
            return false;
        };
        let removed = node.attributes.remove(&name.to_ascii_lowercase()).is_some();
        if removed {
            self.mark(
                node_id,
                DirtyFlags::attributes(),
                DomMutationKind::RemoveAttribute {
                    name: name.to_owned(),
                },
            );
        }
        removed
    }

    /// Sets node text.
    #[must_use]
    pub fn set_text(&mut self, node_id: DomNodeId, value: impl Into<String>) -> bool {
        let value = value.into();
        let Some(node) = self.nodes.get_mut(&node_id) else {
            return false;
        };
        node.text.clone_from(&value);
        self.mark(
            node_id,
            DirtyFlags::text(),
            DomMutationKind::SetText { value },
        );
        true
    }

    /// Appends a synthetic text child to a node.
    #[must_use]
    pub fn append_text_child(
        &mut self,
        parent: DomNodeId,
        value: impl Into<String>,
    ) -> Option<DomNodeId> {
        if !self.nodes.contains_key(&parent) {
            return None;
        }
        let id = self.alloc_node_id();
        let mut node = DomNode::new(id, DomNodeKind::Text, "#text");
        node.parent = Some(parent);
        node.text = value.into();
        self.nodes.insert(id, node);
        if let Some(parent_node) = self.nodes.get_mut(&parent) {
            parent_node.children.push(id);
        }
        self.mark(
            parent,
            DirtyFlags::structure(),
            DomMutationKind::InsertNode { parent, node: id },
        );
        Some(id)
    }

    /// Sets form-control focus.
    #[must_use]
    pub fn focus_control(&mut self, control_id: Option<u64>) -> bool {
        if let Some(control_id) = control_id {
            if self.node_for_control(control_id).is_none() {
                return false;
            }
        }

        if self.focused_control_id == control_id {
            return true;
        }

        self.focused_control_id = control_id;
        let target = control_id
            .and_then(|id| self.node_for_control(id))
            .unwrap_or(self.root);
        self.mark(
            target,
            DirtyFlags::focus(),
            DomMutationKind::SetFocus { control_id },
        );
        true
    }

    /// Updates one form-control value in the runtime.
    #[must_use]
    pub fn set_form_value(&mut self, control_id: u64, value: impl Into<String>) -> bool {
        let value = value.into();
        let Some(node_id) = self.node_for_control(control_id) else {
            return false;
        };
        if let Some(node) = self.nodes.get(&node_id) {
            if node.text == value {
                return true;
            }
        }

        if let Some(node) = self.nodes.get_mut(&node_id) {
            node.text.clone_from(&value);
            node.attributes.insert("value".to_owned(), value.clone());
        }
        self.mark(
            node_id,
            DirtyFlags::text(),
            DomMutationKind::SetFormValue { control_id, value },
        );
        true
    }

    /// Synchronizes runtime form values/focus from a render document.
    pub fn sync_from_render_document(&mut self, document: &RenderDocument) {
        let mut focused = None;

        for block in &document.blocks {
            let RenderBlock::Form(form) = block else {
                continue;
            };
            for control in &form.controls {
                let _ = self.set_form_value(control.id, control.value.clone());
                if control.focused {
                    focused = Some(control.id);
                }
            }
        }

        let _ = self.focus_control(focused);
    }

    /// Applies runtime form values/focus back into a render document.
    pub fn apply_to_render_document(&self, document: &mut RenderDocument) {
        for block in &mut document.blocks {
            let RenderBlock::Form(form) = block else {
                continue;
            };
            for control in &mut form.controls {
                if let Some(node_id) = self.node_for_control(control.id) {
                    if let Some(node) = self.nodes.get(&node_id) {
                        control.value.clone_from(&node.text);
                    }
                }
                control.focused = self.focused_control_id == Some(control.id);
            }
        }
    }

    /// Dispatches an event, queues script hooks, and computes a default action.
    pub fn dispatch_event(&mut self, mut event: DomEvent) -> EventDispatchResult {
        event.id = self.next_event_id;
        self.next_event_id = self.next_event_id.wrapping_add(1).max(1);

        self.script_hooks.push(
            event.kind,
            event.target,
            format!("queued script hook for {:?}", event.kind),
        );

        let dirty = match event.kind {
            DomEventKind::Focus | DomEventKind::Blur => DirtyFlags::focus(),
            DomEventKind::Input | DomEventKind::Change | DomEventKind::BeforeInput => {
                DirtyFlags::text()
            }
            DomEventKind::Submit | DomEventKind::Click | DomEventKind::KeyDown => {
                DirtyFlags::paint()
            }
        };

        self.mark(
            event.target,
            dirty,
            DomMutationKind::DispatchEvent { event: event.kind },
        );

        let default_action = if event.default_prevented {
            None
        } else {
            Self::default_action_for_event(&event)
        };

        EventDispatchResult {
            event,
            default_action,
            dirty,
        }
    }

    /// Finds the runtime node for a form control.
    #[must_use]
    pub fn node_for_control(&self, control_id: u64) -> Option<DomNodeId> {
        self.nodes
            .values()
            .find(|node| node.control_id == Some(control_id))
            .map(|node| node.id)
    }

    /// Finds the runtime node for a link href/text pair.
    #[must_use]
    pub fn node_for_link(&self, href: &str, text: &str) -> Option<DomNodeId> {
        self.nodes.values().find_map(|node| {
            if node.kind != DomNodeKind::Link {
                return None;
            }
            let node_href = node
                .attributes
                .get("href")
                .map(String::as_str)
                .unwrap_or_default();
            (node_href == href && (text.is_empty() || node.text == text)).then_some(node.id)
        })
    }

    fn default_action_for_event(event: &DomEvent) -> Option<DefaultAction> {
        match (&event.kind, &event.payload) {
            (DomEventKind::Click, DomEventPayload::Link { href, .. }) => {
                Some(DefaultAction::Navigate(href.clone()))
            }
            (
                DomEventKind::Click,
                DomEventPayload::FormControl {
                    control_id, kind, ..
                },
            ) if kind.is_text_editable() => Some(DefaultAction::FocusControl(*control_id)),
            (
                DomEventKind::Click,
                DomEventPayload::FormControl {
                    form_id: Some(form_id),
                    control_id,
                    kind,
                    ..
                },
            ) if kind.is_submit_like() => Some(DefaultAction::SubmitForm {
                form_id: *form_id,
                submit_control_id: Some(*control_id),
            }),
            (DomEventKind::Submit, DomEventPayload::FormSubmit { form_id, .. }) => {
                Some(DefaultAction::SubmitForm {
                    form_id: *form_id,
                    submit_control_id: None,
                })
            }
            _ => None,
        }
    }

    fn add_block_node(
        &mut self,
        parent: DomNodeId,
        index: usize,
        block: &RenderBlock,
    ) -> DomNodeId {
        match block {
            RenderBlock::Heading { level, text } => {
                let id = self.add_node(parent, DomNodeKind::Block, format!("h{level}"));
                self.decorate_block(id, index, text);
                id
            }
            RenderBlock::Paragraph { text } => {
                let id = self.add_node(parent, DomNodeKind::Block, "p");
                self.decorate_block(id, index, text);
                id
            }
            RenderBlock::Link { text, href } => {
                let id = self.add_node(parent, DomNodeKind::Link, "a");
                self.decorate_block(id, index, text);
                if let Some(href) = href {
                    let _ = self.set_attribute_without_record(id, "href", href);
                }
                id
            }
            RenderBlock::InlineFlow { fragments } => {
                let id = self.add_node(parent, DomNodeKind::Block, "p");
                if let Some(node) = self.nodes.get_mut(&id) {
                    node.block_index = Some(index);
                }
                for fragment in fragments {
                    match fragment {
                        crate::InlineFragment::Text { text } => {
                            let child = self.add_node(id, DomNodeKind::Text, "#text");
                            if let Some(node) = self.nodes.get_mut(&child) {
                                node.text.clone_from(text);
                            }
                        }
                        crate::InlineFragment::Link { text, href } => {
                            let child = self.add_node(id, DomNodeKind::Link, "a");
                            if let Some(node) = self.nodes.get_mut(&child) {
                                node.text.clone_from(text);
                            }
                            if let Some(href) = href {
                                let _ = self.set_attribute_without_record(child, "href", href);
                            }
                        }
                    }
                }
                id
            }
            RenderBlock::Image { alt, src } => {
                let id = self.add_node(parent, DomNodeKind::Image, "img");
                if let Some(node) = self.nodes.get_mut(&id) {
                    node.block_index = Some(index);
                    node.text = alt.clone().unwrap_or_default();
                }
                if let Some(src) = src {
                    let _ = self.set_attribute_without_record(id, "src", src);
                }
                if let Some(alt) = alt {
                    let _ = self.set_attribute_without_record(id, "alt", alt);
                }
                id
            }
            RenderBlock::Form(form) => self.add_form_node(parent, index, form),
            RenderBlock::Generic { tag, text } => {
                let id = self.add_node(parent, DomNodeKind::Unknown, tag.clone());
                self.decorate_block(id, index, text);
                id
            }
        }
    }

    fn add_form_node(&mut self, parent: DomNodeId, index: usize, form: &FormBlock) -> DomNodeId {
        let id = self.add_node(parent, DomNodeKind::Form, "form");
        if let Some(node) = self.nodes.get_mut(&id) {
            node.block_index = Some(index);
            node.form_id = Some(form.id);
        }
        if let Some(action) = &form.action {
            let _ = self.set_attribute_without_record(id, "action", action);
        }
        let _ = self.set_attribute_without_record(
            id,
            "method",
            match form.method {
                FormMethod::Get => "get",
                FormMethod::Post => "post",
            },
        );

        for control in &form.controls {
            let child = self.add_node(id, DomNodeKind::FormControl, control_tag(control.kind));
            if let Some(node) = self.nodes.get_mut(&child) {
                node.form_id = Some(form.id);
                node.control_id = Some(control.id);
                node.text.clone_from(&control.value);
            }
            let _ =
                self.set_attribute_without_record(child, "kind", control_kind_name(control.kind));
            if let Some(name) = &control.name {
                let _ = self.set_attribute_without_record(child, "name", name);
            }
            if let Some(placeholder) = &control.placeholder {
                let _ = self.set_attribute_without_record(child, "placeholder", placeholder);
            }
            if control.focused {
                self.focused_control_id = Some(control.id);
            }
        }

        id
    }

    fn decorate_block(&mut self, id: DomNodeId, index: usize, text: &str) {
        if let Some(node) = self.nodes.get_mut(&id) {
            node.block_index = Some(index);
            text.clone_into(&mut node.text);
        }
    }

    fn add_node(
        &mut self,
        parent: DomNodeId,
        kind: DomNodeKind,
        tag: impl Into<String>,
    ) -> DomNodeId {
        let id = self.alloc_node_id();
        let mut node = DomNode::new(id, kind, tag);
        node.parent = Some(parent);
        self.nodes.insert(id, node);
        if let Some(parent_node) = self.nodes.get_mut(&parent) {
            parent_node.children.push(id);
        }
        id
    }

    fn alloc_node_id(&mut self) -> DomNodeId {
        let id = DomNodeId(self.next_node_id);
        self.next_node_id = self.next_node_id.wrapping_add(1).max(2);
        id
    }

    fn set_attribute_without_record(
        &mut self,
        node_id: DomNodeId,
        name: &str,
        value: &str,
    ) -> bool {
        let Some(node) = self.nodes.get_mut(&node_id) else {
            return false;
        };
        node.attributes
            .insert(name.to_ascii_lowercase(), value.to_owned());
        true
    }

    fn mark(&mut self, target: DomNodeId, dirty: DirtyFlags, kind: DomMutationKind) {
        if dirty.any() {
            self.invalidation.mark(target, dirty);
        }
        let sequence = self.sequence;
        self.sequence = self.sequence.wrapping_add(1).max(1);
        self.mutations.push(DomMutation {
            sequence,
            target,
            kind,
            dirty,
        });
    }
}

fn control_tag(kind: FormControlKind) -> &'static str {
    match kind {
        FormControlKind::Text
        | FormControlKind::Search
        | FormControlKind::Password
        | FormControlKind::Hidden
        | FormControlKind::Submit
        | FormControlKind::Button => "input",
        FormControlKind::TextArea => "textarea",
    }
}

fn control_kind_name(kind: FormControlKind) -> &'static str {
    match kind {
        FormControlKind::Text => "text",
        FormControlKind::Search => "search",
        FormControlKind::Password => "password",
        FormControlKind::Hidden => "hidden",
        FormControlKind::Submit => "submit",
        FormControlKind::Button => "button",
        FormControlKind::TextArea => "textarea",
    }
}
